<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

    <!-- Choose a mode: -->
    <!-- OOP mode: -->
<!--    <DefineConstants>$(DefineConstants);OOP_MODE</DefineConstants>-->
    <!-- DDD mode: -->
    <DefineConstants>$(DefineConstants);DDD_MODE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <!-- Authentication / Authorization -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <!-- Token validation primitives (optional but explicit) -->
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  
  <ItemGroup>
    <!-- Entity Framework Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!-- SQLite provider for EF Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="_2_Modules\Bookings\_2_Application\Dtos\Contracts\" />
    <Folder Include="_2_Modules\Cars\_3_Domain\ValueObjects\" />
    <Folder Include="_2_Modules\Customers\_2_Application\Errors\" />
    <Folder Include="_2_Modules\Customers\_3_Domain\Enums\" />
    <Folder Include="_2_Modules\Customers\_3_Domain\Policies\" />
    <Folder Include="_2_Modules\Customers\_3_Domain\ValueObjects\" />
    <Folder Include="_2_Modules\Employees\_2_Application\Dtos\Contracts\" />
    <Folder Include="_2_Modules\Employees\_2_Application\Services\" />
    <Folder Include="_2_Modules\Employees\_3_Domain\Policies\" />
    <Folder Include="_2_Modules\Employees\_3_Domain\ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="_4_BuildingBlocks\Result.cs">
      <DependentUpon>DiAddBuildingBlocks.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
