using CarRentalApi.Modules.Customers.Domain.Aggregates;
using CarRentalApi.Modules.Rentals.Domain.Aggregates;
using CarRentalApi.Modules.Reservations.Domain.Aggregates;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace CarRentalApi.Data.Database;

public sealed class ConfigReservations(
   DateTimeOffsetToIsoStringConverter _dtOffMillis
) : IEntityTypeConfiguration<Reservation> {
   public void Configure(EntityTypeBuilder<Reservation> b) {
      // Tablename
      b.ToTable("Reservations");

      // Primary key
      b.HasKey(x => x.Id); // x: Reservation
      b.Property(x => x.Id).ValueGeneratedNever(); // Guid is generated by Domain, no from DB

      // scalar properties 
      b.Property(x => x.CarCategory).IsRequired();
      b.Property(x => x.CustomerId).IsRequired();
      b.Property(x => x.CreatedAt).IsRequired().HasConversion(_dtOffMillis);
      b.Property(x => x.ConfirmedAt).HasConversion(_dtOffMillis);
      b.Property(x => x.CancelledAt).HasConversion(_dtOffMillis);
      b.Property(x => x.ExpiredAt).HasConversion(_dtOffMillis);
      b.Property(x => x.Status).IsRequired().HasConversion<string>();

      // value object (owned type)
      // Owned: RentalPeriod -> two columns in Reservation table
      b.OwnsOne(r => r.Period, rp => {
         rp.Property(p => p.Start).HasColumnName("Start").HasConversion(_dtOffMillis);
         rp.Property(p => p.End).HasColumnName("End").HasConversion(_dtOffMillis); // no fractional seconds
      });

      // Optional aber oft sinnvoll (damit EF das Owned immer erwartet)
      b.Navigation(x => x.Period).IsRequired();

      // indices
      b.HasIndex(x => x.CarCategory);
      b.HasIndex(x => x.CustomerId);
      b.HasIndex(x => x.Status);

      // Relationship: Customer <-> Reservations (1 : 0..n)
      // --------------------------------------------------
#if OOP_MODE
      // WITH Navigation Properties (OOP-Style)
      b.HasOne(reservation => reservation.Customer) // Reservation has one Customer
         .WithMany(customer => customer.Reservations) // Customer has many Reservations
         .HasForeignKey(reservation => reservation.CustomerId) // FK in Reservation table
         .IsRequired()
         .OnDelete(DeleteBehavior.Restrict);
#elif DDD_MODE
      // WITHOUT Navigation Properties (DDD-Style)
      b.HasOne<Customer>()                      // Reservation has one Customer (without Property)
         .WithMany()                            // Customer has many Reservations (without Collection)
         .HasForeignKey(res => res.CustomerId)  // FK in Reservation table
         .IsRequired()
         .OnDelete(DeleteBehavior.Restrict);
#else
      #error "Define either OOP_MODE or DDD_MODE in .csproj"
#endif
      
      // Relationship: Reservations <-> Rentals (1 : 0..1)
#if OOP_MODE
      b.HasOne(res => res.Rental)               // Reservation has zero or one Rental
         .WithOne(r => r.Reservation)           // Rental has one Reservation
         .HasForeignKey<Reservation>(res => res.RentalId) // FK in Reservation table
         .OnDelete(DeleteBehavior.Restrict);
#elif DDD_MODE
      b.HasOne<Rental>()
         .WithOne()
         .HasForeignKey<Reservation>(res => res.RentalId)
         .OnDelete(DeleteBehavior.Restrict);
#else
      #error "Define either OOP_MODE or DDD_MODE in .csproj"
#endif
   }
}